"""Common rules that apply to all server roles."""

from infra_auditor.rules.base import Rule


def _gte_comparator(current: str, recommended: str) -> bool:
    """Check if current >= recommended (numeric)."""
    try:
        return int(current) >= int(recommended)
    except (ValueError, TypeError):
        return False


def _lte_comparator(current: str, recommended: str) -> bool:
    """Check if current <= recommended (numeric)."""
    try:
        return int(current) <= int(recommended)
    except (ValueError, TypeError):
        return False


COMMON_RULES = [
    # CPU
    Rule(
        category="cpu",
        subcategory="governor",
        item="scaling_governor",
        description="CPU 주파수 조절 정책",
        recommended_value="performance",
        collection_method="cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor",
        severity="warning",
        impact_description="주파수 변경으로 인한 지연 시간 변동성 증가",
        justification="일관된 성능과 낮은 지연시간을 위해 performance 모드 권장",
        remediation_command="echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor",
        remediation_persistent='echo \'GOVERNOR="performance"\' | sudo tee /etc/default/cpufrequtils',
        score_impact=10,
        value_extractor=lambda d: d.get("cpu", {}).get("governor", "unknown"),
    ),
    Rule(
        category="cpu",
        subcategory="power",
        item="max_cstate",
        description="CPU C-state 최대 깊이",
        recommended_value="1",
        collection_method="cat /sys/module/intel_idle/parameters/max_cstate",
        severity="warning",
        impact_description="깊은 절전 상태로 인한 wakeup 지연 발생",
        justification="C-state 1 이하로 제한하여 지연시간 최소화",
        remediation_command="",
        remediation_persistent="GRUB_CMDLINE에 intel_idle.max_cstate=1 추가",
        requires_reboot=True,
        score_impact=8,
        value_extractor=lambda d: d.get("cpu", {}).get("max_cstate", "unknown"),
        comparator=_lte_comparator,
    ),
    Rule(
        category="cpu",
        subcategory="numa",
        item="numa_balancing",
        description="자동 NUMA 밸런싱",
        recommended_value="0",
        collection_method="cat /proc/sys/kernel/numa_balancing",
        severity="warning",
        impact_description="자동 NUMA 밸런싱은 예측 불가능한 성능 저하 야기",
        justification="수동 NUMA 제어가 더 안정적인 성능 제공",
        remediation_command="sysctl -w kernel.numa_balancing=0",
        remediation_persistent="echo 'kernel.numa_balancing = 0' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("memory", {}).get("numa_balancing", "unknown"),
    ),
    # Memory
    Rule(
        category="memory",
        subcategory="virtual_memory",
        item="vm.swappiness",
        description="스왑 사용 적극성 설정",
        recommended_value="1",
        collection_method="cat /proc/sys/vm/swappiness",
        severity="critical",
        impact_description="높은 swappiness로 인한 불필요한 스왑 발생",
        justification="메모리 부족 시에만 스왑 사용하여 성능 보장",
        remediation_command="sysctl -w vm.swappiness=1",
        remediation_persistent="echo 'vm.swappiness = 1' >> /etc/sysctl.conf",
        score_impact=25,
        value_extractor=lambda d: d.get("memory", {}).get("swappiness", "unknown"),
        comparator=_lte_comparator,
    ),
    Rule(
        category="memory",
        subcategory="virtual_memory",
        item="vm.dirty_ratio",
        description="더티 페이지 비율 상한",
        recommended_value="15",
        collection_method="cat /proc/sys/vm/dirty_ratio",
        severity="warning",
        impact_description="높은 dirty_ratio로 인한 I/O 스톰 위험",
        justification="쓰기 성능과 안정성의 균형",
        remediation_command="sysctl -w vm.dirty_ratio=15",
        remediation_persistent="echo 'vm.dirty_ratio = 15' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("memory", {}).get("dirty_ratio", "unknown"),
        comparator=_lte_comparator,
    ),
    Rule(
        category="memory",
        subcategory="virtual_memory",
        item="vm.dirty_background_ratio",
        description="백그라운드 더티 페이지 비율",
        recommended_value="5",
        collection_method="cat /proc/sys/vm/dirty_background_ratio",
        severity="warning",
        impact_description="지연된 백그라운드 플러시로 인한 I/O 누적",
        justification="적극적 백그라운드 플러시로 쓰기 지연 최소화",
        remediation_command="sysctl -w vm.dirty_background_ratio=5",
        remediation_persistent="echo 'vm.dirty_background_ratio = 5' >> /etc/sysctl.conf",
        score_impact=5,
        value_extractor=lambda d: d.get("memory", {}).get("dirty_background_ratio", "unknown"),
        comparator=_lte_comparator,
    ),
    Rule(
        category="memory",
        subcategory="virtual_memory",
        item="vm.overcommit_memory",
        description="메모리 오버커밋 정책",
        recommended_value="1",
        collection_method="cat /proc/sys/vm/overcommit_memory",
        severity="info",
        impact_description="보수적 오버커밋으로 일부 애플리케이션 메모리 할당 실패 가능",
        justification="합리적 메모리 오버커밋 허용",
        remediation_command="sysctl -w vm.overcommit_memory=1",
        remediation_persistent="echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf",
        score_impact=3,
        value_extractor=lambda d: d.get("memory", {}).get("overcommit_memory", "unknown"),
    ),
    # Network
    Rule(
        category="network",
        subcategory="tcp",
        item="net.core.somaxconn",
        description="소켓 연결 대기 큐 크기",
        recommended_value="65535",
        collection_method="cat /proc/sys/net/core/somaxconn",
        severity="warning",
        impact_description="연결 대기 큐 부족으로 연결 거부 발생 가능",
        justification="대량 연결 처리를 위한 큐 확장",
        remediation_command="sysctl -w net.core.somaxconn=65535",
        remediation_persistent="echo 'net.core.somaxconn = 65535' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.core.somaxconn", "unknown"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="network",
        subcategory="tcp",
        item="net.core.netdev_max_backlog",
        description="네트워크 디바이스 백로그 큐",
        recommended_value="5000",
        collection_method="cat /proc/sys/net/core/netdev_max_backlog",
        severity="warning",
        impact_description="패킷 드롭 발생 가능",
        justification="고속 NIC에서 패킷 드롭 방지",
        remediation_command="sysctl -w net.core.netdev_max_backlog=5000",
        remediation_persistent="echo 'net.core.netdev_max_backlog = 5000' >> /etc/sysctl.conf",
        score_impact=5,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.core.netdev_max_backlog", "unknown"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="network",
        subcategory="tcp",
        item="net.ipv4.tcp_congestion_control",
        description="TCP 혼잡 제어 알고리즘",
        recommended_value="bbr",
        collection_method="cat /proc/sys/net/ipv4/tcp_congestion_control",
        severity="info",
        impact_description="레거시 혼잡 제어로 최적이 아닌 throughput",
        justification="BBR은 최신 혼잡 제어 알고리즘으로 처리량 향상",
        remediation_command="sysctl -w net.ipv4.tcp_congestion_control=bbr",
        remediation_persistent="echo 'net.ipv4.tcp_congestion_control = bbr' >> /etc/sysctl.conf",
        score_impact=5,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.ipv4.tcp_congestion_control", "unknown"),
    ),
    # Kernel limits
    Rule(
        category="kernel",
        subcategory="limits",
        item="fs.file-max",
        description="시스템 전체 최대 파일 핸들 수",
        recommended_value="2000000",
        collection_method="cat /proc/sys/fs/file-max",
        severity="warning",
        impact_description="파일 핸들 부족으로 서비스 장애 가능",
        justification="대량 파일 핸들 지원",
        remediation_command="sysctl -w fs.file-max=2000000",
        remediation_persistent="echo 'fs.file-max = 2000000' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("kernel", {}).get("file_max", "unknown"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="kernel",
        subcategory="limits",
        item="kernel.pid_max",
        description="최대 PID 값",
        recommended_value="4194304",
        collection_method="cat /proc/sys/kernel/pid_max",
        severity="info",
        impact_description="PID 고갈로 프로세스 생성 실패 가능",
        justification="대량 프로세스 지원",
        remediation_command="sysctl -w kernel.pid_max=4194304",
        remediation_persistent="echo 'kernel.pid_max = 4194304' >> /etc/sysctl.conf",
        score_impact=3,
        value_extractor=lambda d: d.get("kernel", {}).get("pid_max", "unknown"),
        comparator=_gte_comparator,
    ),
]
