"""Common rules that apply to all server roles."""

from infra_auditor.rules.base import Rule


def _gte_comparator(current: str, recommended: str) -> bool:
    """Check if current >= recommended (numeric)."""
    try:
        return int(current) >= int(recommended)
    except (ValueError, TypeError):
        return False


def _lte_comparator(current: str, recommended: str) -> bool:
    """Check if current <= recommended (numeric)."""
    try:
        return int(current) <= int(recommended)
    except (ValueError, TypeError):
        return False


COMMON_RULES = [
    # CPU
    Rule(
        category="cpu",
        subcategory="governor",
        item="scaling_governor",
        description="CPU 주파수 조절 정책",
        recommended_value="performance",
        collection_method="cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor",
        severity="warning",
        impact_description="주파수 변경으로 인한 지연 시간 변동성 증가",
        justification="일관된 성능과 낮은 지연시간을 위해 performance 모드 권장",
        remediation_command="echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor",
        remediation_persistent='echo \'GOVERNOR="performance"\' | sudo tee /etc/default/cpufrequtils',
        score_impact=10,
        value_extractor=lambda d: d.get("cpu", {}).get("governor", "unknown"),
    ),
    Rule(
        category="cpu",
        subcategory="power",
        item="max_cstate",
        description="CPU C-state 최대 깊이",
        recommended_value="1",
        collection_method="cat /sys/module/intel_idle/parameters/max_cstate",
        severity="warning",
        impact_description="깊은 절전 상태로 인한 wakeup 지연 발생",
        justification="C-state 1 이하로 제한하여 지연시간 최소화",
        remediation_command="",
        remediation_persistent="GRUB_CMDLINE에 intel_idle.max_cstate=1 추가",
        requires_reboot=True,
        score_impact=8,
        value_extractor=lambda d: d.get("cpu", {}).get("max_cstate", "unknown"),
        comparator=_lte_comparator,
    ),
    Rule(
        category="cpu",
        subcategory="numa",
        item="numa_balancing",
        description="자동 NUMA 밸런싱",
        recommended_value="0",
        collection_method="cat /proc/sys/kernel/numa_balancing",
        severity="warning",
        impact_description="자동 NUMA 밸런싱은 예측 불가능한 성능 저하 야기",
        justification="수동 NUMA 제어가 더 안정적인 성능 제공",
        remediation_command="sysctl -w kernel.numa_balancing=0",
        remediation_persistent="echo 'kernel.numa_balancing = 0' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("memory", {}).get("numa_balancing", "unknown"),
    ),
    # Memory
    Rule(
        category="memory",
        subcategory="virtual_memory",
        item="vm.swappiness",
        description="스왑 사용 적극성 설정",
        recommended_value="1",
        collection_method="cat /proc/sys/vm/swappiness",
        severity="critical",
        impact_description="높은 swappiness로 인한 불필요한 스왑 발생",
        justification="메모리 부족 시에만 스왑 사용하여 성능 보장",
        remediation_command="sysctl -w vm.swappiness=1",
        remediation_persistent="echo 'vm.swappiness = 1' >> /etc/sysctl.conf",
        score_impact=25,
        value_extractor=lambda d: d.get("memory", {}).get("swappiness", "unknown"),
        comparator=_lte_comparator,
    ),
    Rule(
        category="memory",
        subcategory="virtual_memory",
        item="vm.dirty_ratio",
        description="더티 페이지 비율 상한",
        recommended_value="15",
        collection_method="cat /proc/sys/vm/dirty_ratio",
        severity="warning",
        impact_description="높은 dirty_ratio로 인한 I/O 스톰 위험",
        justification="쓰기 성능과 안정성의 균형",
        remediation_command="sysctl -w vm.dirty_ratio=15",
        remediation_persistent="echo 'vm.dirty_ratio = 15' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("memory", {}).get("dirty_ratio", "unknown"),
        comparator=_lte_comparator,
    ),
    Rule(
        category="memory",
        subcategory="virtual_memory",
        item="vm.dirty_background_ratio",
        description="백그라운드 더티 페이지 비율",
        recommended_value="5",
        collection_method="cat /proc/sys/vm/dirty_background_ratio",
        severity="warning",
        impact_description="지연된 백그라운드 플러시로 인한 I/O 누적",
        justification="적극적 백그라운드 플러시로 쓰기 지연 최소화",
        remediation_command="sysctl -w vm.dirty_background_ratio=5",
        remediation_persistent="echo 'vm.dirty_background_ratio = 5' >> /etc/sysctl.conf",
        score_impact=5,
        value_extractor=lambda d: d.get("memory", {}).get("dirty_background_ratio", "unknown"),
        comparator=_lte_comparator,
    ),
    Rule(
        category="memory",
        subcategory="virtual_memory",
        item="vm.overcommit_memory",
        description="메모리 오버커밋 정책",
        recommended_value="1",
        collection_method="cat /proc/sys/vm/overcommit_memory",
        severity="info",
        impact_description="보수적 오버커밋으로 일부 애플리케이션 메모리 할당 실패 가능",
        justification="합리적 메모리 오버커밋 허용",
        remediation_command="sysctl -w vm.overcommit_memory=1",
        remediation_persistent="echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf",
        score_impact=3,
        value_extractor=lambda d: d.get("memory", {}).get("overcommit_memory", "unknown"),
    ),
    # Network
    Rule(
        category="network",
        subcategory="tcp",
        item="net.core.somaxconn",
        description="소켓 연결 대기 큐 크기",
        recommended_value="65535",
        collection_method="cat /proc/sys/net/core/somaxconn",
        severity="warning",
        impact_description="연결 대기 큐 부족으로 연결 거부 발생 가능",
        justification="대량 연결 처리를 위한 큐 확장",
        remediation_command="sysctl -w net.core.somaxconn=65535",
        remediation_persistent="echo 'net.core.somaxconn = 65535' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.core.somaxconn", "unknown"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="network",
        subcategory="tcp",
        item="net.core.netdev_max_backlog",
        description="네트워크 디바이스 백로그 큐",
        recommended_value="5000",
        collection_method="cat /proc/sys/net/core/netdev_max_backlog",
        severity="warning",
        impact_description="패킷 드롭 발생 가능",
        justification="고속 NIC에서 패킷 드롭 방지",
        remediation_command="sysctl -w net.core.netdev_max_backlog=5000",
        remediation_persistent="echo 'net.core.netdev_max_backlog = 5000' >> /etc/sysctl.conf",
        score_impact=5,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.core.netdev_max_backlog", "unknown"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="network",
        subcategory="tcp",
        item="net.ipv4.tcp_congestion_control",
        description="TCP 혼잡 제어 알고리즘",
        recommended_value="bbr",
        collection_method="cat /proc/sys/net/ipv4/tcp_congestion_control",
        severity="info",
        impact_description="레거시 혼잡 제어로 최적이 아닌 throughput",
        justification="BBR은 최신 혼잡 제어 알고리즘으로 처리량 향상",
        remediation_command="sysctl -w net.ipv4.tcp_congestion_control=bbr",
        remediation_persistent="echo 'net.ipv4.tcp_congestion_control = bbr' >> /etc/sysctl.conf",
        score_impact=5,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.ipv4.tcp_congestion_control", "unknown"),
    ),
    # Kernel limits
    Rule(
        category="kernel",
        subcategory="limits",
        item="fs.file-max",
        description="시스템 전체 최대 파일 핸들 수",
        recommended_value="2000000",
        collection_method="cat /proc/sys/fs/file-max",
        severity="warning",
        impact_description="파일 핸들 부족으로 서비스 장애 가능",
        justification="대량 파일 핸들 지원",
        remediation_command="sysctl -w fs.file-max=2000000",
        remediation_persistent="echo 'fs.file-max = 2000000' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("kernel", {}).get("file_max", "unknown"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="kernel",
        subcategory="limits",
        item="kernel.pid_max",
        description="최대 PID 값",
        recommended_value="4194304",
        collection_method="cat /proc/sys/kernel/pid_max",
        severity="info",
        impact_description="PID 고갈로 프로세스 생성 실패 가능",
        justification="대량 프로세스 지원",
        remediation_command="sysctl -w kernel.pid_max=4194304",
        remediation_persistent="echo 'kernel.pid_max = 4194304' >> /etc/sysctl.conf",
        score_impact=3,
        value_extractor=lambda d: d.get("kernel", {}).get("pid_max", "unknown"),
        comparator=_gte_comparator,
    ),
    
    # Advanced Network Tuning
    Rule(
        category="network",
        subcategory="scaling",
        item="rps_sock_flow_entries",
        description="RFS (Receive Flow Steering) 글로벌 플로우 테이블 크기",
        recommended_value="32768",
        collection_method="cat /proc/sys/net/core/rps_sock_flow_entries",
        severity="info",
        impact_description="패킷 처리 CPU 분산 효율성 저하",
        justification="CPU당 1024개 플로우로 설정하여 RFS 성능 최적화",
        remediation_command="sysctl -w net.core.rps_sock_flow_entries=32768",
        remediation_persistent="echo 'net.core.rps_sock_flow_entries = 32768' >> /etc/sysctl.conf",
        score_impact=5,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.core.rps_sock_flow_entries", "0"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="network",
        subcategory="budget",
        item="netdev_budget",
        description="네트워크 패킷 처리 예산",
        recommended_value="600",
        collection_method="cat /proc/sys/net/core/netdev_budget",
        severity="info",
        impact_description="패킷 드롭 증가 가능성",
        justification="높은 네트워크 로드에서 패킷 처리량 증대",
        remediation_command="sysctl -w net.core.netdev_budget=600",
        remediation_persistent="echo 'net.core.netdev_budget = 600' >> /etc/sysctl.conf",
        score_impact=3,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.core.netdev_budget", "300"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="network",
        subcategory="conntrack",
        item="nf_conntrack_max",
        description="커넥션 트래킹 최대 연결 수",
        recommended_value="1048576",
        collection_method="cat /proc/sys/net/netfilter/nf_conntrack_max",
        severity="warning",
        impact_description="새 연결 거부 및 네트워크 서비스 중단",
        justification="대용량 서버 환경에서 연결 추적 한계 증대",
        remediation_command="sysctl -w net.netfilter.nf_conntrack_max=1048576",
        remediation_persistent="echo 'net.netfilter.nf_conntrack_max = 1048576' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.netfilter.nf_conntrack_max", "65536"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="network",
        subcategory="tcp",
        item="tcp_window_scaling",
        description="TCP 윈도우 스케일링 활성화",
        recommended_value="1",
        collection_method="cat /proc/sys/net/ipv4/tcp_window_scaling",
        severity="warning",
        impact_description="높은 대역폭-지연 곱 네트워크에서 처리량 저하",
        justification="고성능 네트워크에서 TCP 처리량 최대화",
        remediation_command="sysctl -w net.ipv4.tcp_window_scaling=1",
        remediation_persistent="echo 'net.ipv4.tcp_window_scaling = 1' >> /etc/sysctl.conf",
        score_impact=7,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.ipv4.tcp_window_scaling", "0"),
    ),
    Rule(
        category="network",
        subcategory="arp",
        item="neigh_gc_thresh3",
        description="ARP 테이블 하드 한계",
        recommended_value="8192",
        collection_method="cat /proc/sys/net/ipv4/neigh/default/gc_thresh3",
        severity="info",
        impact_description="대규모 네트워크에서 ARP 테이블 오버플로우",
        justification="많은 이웃 노드가 있는 환경에서 ARP 테이블 크기 증대",
        remediation_command="sysctl -w net.ipv4.neigh.default.gc_thresh3=8192",
        remediation_persistent="echo 'net.ipv4.neigh.default.gc_thresh3 = 8192' >> /etc/sysctl.conf",
        score_impact=4,
        value_extractor=lambda d: d.get("network", {}).get("sysctl", {}).get("net.ipv4.neigh.default.gc_thresh3", "1024"),
        comparator=_gte_comparator,
    ),

    # Memory Management Advanced Rules
    Rule(
        category="memory",
        subcategory="hugepages",
        item="transparent_hugepage",
        description="Transparent Hugepages 설정",
        recommended_value="madvise",
        collection_method="cat /sys/kernel/mm/transparent_hugepage/enabled",
        severity="warning",
        impact_description="예측할 수 없는 메모리 지연과 파편화",
        justification="애플리케이션별 제어 가능한 madvise 모드 권장",
        remediation_command="echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled",
        remediation_persistent="GRUB_CMDLINE에 transparent_hugepage=madvise 추가",
        score_impact=6,
        value_extractor=lambda d: d.get("memory", {}).get("transparent_hugepage", "always"),
    ),
    Rule(
        category="memory",
        subcategory="tuning",
        item="min_free_kbytes",
        description="최소 여유 메모리 (대용량 RAM 환경)",
        recommended_value="1048576",  # 1GB for systems with >1TB RAM
        collection_method="cat /proc/sys/vm/min_free_kbytes",
        severity="info",
        impact_description="메모리 할당 실패 및 시스템 불안정성",
        justification="대용량 RAM 시스템에서 메모리 할당 안정성 보장",
        remediation_command="sysctl -w vm.min_free_kbytes=1048576",
        remediation_persistent="echo 'vm.min_free_kbytes = 1048576' >> /etc/sysctl.conf",
        score_impact=5,
        value_extractor=lambda d: d.get("memory", {}).get("min_free_kbytes", "67584"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="memory",
        subcategory="numa",
        item="zone_reclaim_mode",
        description="NUMA zone reclaim 모드",
        recommended_value="0",
        collection_method="cat /proc/sys/vm/zone_reclaim_mode",
        severity="warning",
        impact_description="불필요한 로컬 메모리 회수로 성능 저하",
        justification="NUMA 시스템에서 원격 메모리 접근이 로컬 회수보다 효율적",
        remediation_command="sysctl -w vm.zone_reclaim_mode=0",
        remediation_persistent="echo 'vm.zone_reclaim_mode = 0' >> /etc/sysctl.conf",
        score_impact=7,
        value_extractor=lambda d: d.get("memory", {}).get("zone_reclaim_mode", "1"),
    ),

    # Kernel Advanced Tuning
    Rule(
        category="kernel",
        subcategory="scheduler",
        item="sched_migration_cost_ns",
        description="스케줄러 마이그레이션 비용",
        recommended_value="5000000",
        collection_method="cat /proc/sys/kernel/sched_migration_cost_ns",
        severity="info",
        impact_description="과도한 CPU 간 태스크 마이그레이션",
        justification="고성능 CPU에서 마이그레이션 빈도 조절",
        remediation_command="sysctl -w kernel.sched_migration_cost_ns=5000000",
        remediation_persistent="echo 'kernel.sched_migration_cost_ns = 5000000' >> /etc/sysctl.conf",
        score_impact=3,
        value_extractor=lambda d: d.get("kernel", {}).get("scheduler", {}).get("kernel.sched_migration_cost_ns", "500000"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="kernel",
        subcategory="panic",
        item="panic_on_oops",
        description="커널 OOPS 발생 시 패닉",
        recommended_value="1",
        collection_method="cat /proc/sys/kernel/panic_on_oops",
        severity="warning",
        impact_description="커널 오류 후 시스템 불안정 상태 지속",
        justification="커널 오류 발생 시 즉시 재시작하여 서비스 복구",
        remediation_command="sysctl -w kernel.panic_on_oops=1",
        remediation_persistent="echo 'kernel.panic_on_oops = 1' >> /etc/sysctl.conf",
        score_impact=8,
        value_extractor=lambda d: d.get("kernel", {}).get("panic", {}).get("kernel.panic_on_oops", "0"),
    ),
    Rule(
        category="kernel",
        subcategory="limits",
        item="fs_aio_max_nr",
        description="비동기 I/O 최대 요청 수",
        recommended_value="1048576",
        collection_method="cat /proc/sys/fs/aio-max-nr",
        severity="warning",
        impact_description="고성능 I/O 애플리케이션에서 처리량 제한",
        justification="Ceph, 데이터베이스 등 AIO 집약적 애플리케이션 지원",
        remediation_command="sysctl -w fs.aio-max-nr=1048576",
        remediation_persistent="echo 'fs.aio-max-nr = 1048576' >> /etc/sysctl.conf",
        score_impact=6,
        value_extractor=lambda d: d.get("storage", {}).get("filesystem_tuning", {}).get("aio_max_nr", "65536"),
        comparator=_gte_comparator,
    ),
    Rule(
        category="kernel",
        subcategory="inotify",
        item="fs_inotify_max_user_watches",
        description="inotify 최대 감시 수",
        recommended_value="1048576",
        collection_method="cat /proc/sys/fs/inotify/max_user_watches",
        severity="info",
        impact_description="파일 시스템 모니터링 애플리케이션 제한",
        justification="컨테이너 환경 및 파일 모니터링 시스템 지원",
        remediation_command="sysctl -w fs.inotify.max_user_watches=1048576",
        remediation_persistent="echo 'fs.inotify.max_user_watches = 1048576' >> /etc/sysctl.conf",
        score_impact=3,
        value_extractor=lambda d: d.get("storage", {}).get("filesystem_tuning", {}).get("inotify_max_user_watches", "8192"),
        comparator=_gte_comparator,
    ),
]
